import { ReactComponent as Women } from '../../images/dropDownMenu/women.svg';
import { ReactComponent as Men } from '../../images/dropDownMenu/men.svg';
import { ReactComponent as Sport } from '../../images/dropDownMenu/sport.svg';
import { ReactComponent as Kids } from '../../images/dropDownMenu/kids.svg';
const menuItems = [
  {
    id: 1,
    name: 'Жінкам',
    link: '/women',
    icon: <Women style={{ width: '30px', height: '30px' }} />,
    alt: 'alt',
    submenu: [
      { id: 1, name: 'Верхній одяг', link: '/women/верхній одяг' },
      { id: 2, name: 'Плаття', link: '/women/труси' },
      { id: 3, name: 'Спідниці', link: '/women/рубашки' },
      { id: 4, name: 'Майки і футболки', link: '/women/верхній одяг' },
      { id: 5, name: 'Сорочки та блузи', link: '/women/верхній одяг' },
      { id: 6, name: 'Кофти', link: '/women/верхній одяг' },
      { id: 7, name: 'Нижня білизна', link: '/women/верхній одяг' },
      { id: 8, name: 'Аксесуари', link: '/women/верхній одяг' },
      { id: 9, name: 'Інші речі', link: '/women/верхній одяг' },
      { id: 10, name: 'Спортивний одяг', link: '/women/верхній одяг' },
      { id: 11, name: 'Костюми', link: '/women/верхній одяг' },
      { id: 12, name: 'Комбінезони', link: '/women/верхній одяг' },
      { id: 13, name: 'Одяг для дому та сну', link: '/women/верхній одяг' },
      { id: 14, name: 'Спецодяг', link: '/women/верхній одяг' },
      { id: 15, name: 'Для вагітних', link: '/women/верхній одяг' },
      { id: 16, name: 'Штани та шорти', link: '/women/верхній одяг' },
    ],
  },
  {
    id: 2,
    name: 'Чоловікам',
    link: '/men',
    icon: <Men style={{ width: '30px', height: '30px' }} />,
    submenu: [
      { id: 1, name: 'Верхній одяг', link: '/men/верхній одяг' },
      { id: 2, name: 'Піджаки і костюми', link: '/men/труси' },
      { id: 3, name: 'Кофти та Светри', link: '/men/рубашки' },
      { id: 4, name: 'Сорочки та теніски', link: '/men/верхній одяг' },
      { id: 5, name: 'Футболки та майки', link: '/men/верхній одяг' },
      { id: 6, name: 'Нижня білизна', link: '/men/верхній одяг' },
      { id: 7, name: 'Взуття', link: '/men/верхній одяг' },
      { id: 8, name: 'Аксесуари', link: '/men/верхній одяг' },
      { id: 9, name: 'Спортивний одяг', link: '/men/верхній одяг' },
      { id: 10, name: 'Одяг для дому та сну', link: '/men/верхній одяг' },
      { id: 11, name: 'Спецодяг', link: '/men/верхній одяг' },
      { id: 12, name: 'Тактичний одяг', link: '/men/верхній одяг' },
      { id: 13, name: 'Штани та шорти', link: '/men/верхній одяг' },
    ],
  },
  {
    id: 3,
    name: 'Дитячі товари',
    link: '/children',
    icon: <Kids style={{ width: '30px', height: '30px' }} />,
    submenu: [
      { id: 1, name: 'Дитяча кімната', link: '/children/верхній одяг' },
      { id: 2, name: 'Товари для мам', link: '/children/труси' },
      { id: 3, name: 'Харчування і годування', link: '/children/рубашки' },
      { id: 4, name: 'Щоденний догляд', link: '/children/рубашки' },
      { id: 5, name: 'Коляски та автокрісла', link: '/children/рубашки' },
      { id: 6, name: 'Дитячі іграшки', link: '/children/рубашки' },
      { id: 7, name: 'Дитячий транспорт', link: '/children/рубашки' },
      { id: 8, name: 'Товари для творчості', link: '/children/рубашки' },
      { id: 9, name: 'Активний відпочинок', link: '/children/рубашки' },
    ],
  },
  {
    id: 4,
    name: 'Краса та здоров`я',
    link: '/beauty_and_health',
    icon: <Sport style={{ width: '30px', height: '30px' }} />,
    submenu: [
      { id: 1, name: 'Чоловіча косметика', link: '/beauty_and_health/верхній одяг' },
      { id: 2, name: 'Аксесуари для краси', link: '/beauty_and_health/труси' },
      { id: 3, name: 'Декоративна косметика', link: '/beauty_and_health/рубашки' },
      { id: 4, name: 'Парфуми', link: '/beauty_and_health/верхній одяг' },
      { id: 5, name: 'Манікюр і педикюр', link: '/beauty_and_health/верхній одяг' },
      { id: 6, name: 'Косметика для волосся', link: '/beauty_and_health/верхній одяг' },
      { id: 7, name: 'Косметика для обличчя', link: '/beauty_and_health/верхній одяг' },
      { id: 8, name: 'Тіло і ванна', link: '/beauty_and_health/верхній одяг' },
      { id: 9, name: 'Догляд за собою', link: '/beauty_and_health/верхній одяг' },
      { id: 10, name: 'Техніка для краси', link: '/beauty_and_health/верхній одяг' },
      { id: 11, name: 'Подарункові набори', link: '/beauty_and_health/верхній одяг' },
      { id: 12, name: 'Дезінфікуючи засоби', link: '/beauty_and_health/верхній одяг' },
      { id: 13, name: 'Медичні прилади', link: '/beauty_and_health/верхній одяг' },
      { id: 14, name: 'Домашня аптека', link: '/beauty_and_health/верхній одяг' },
      { id: 15, name: 'Оптика', link: '/beauty_and_health/верхній одяг' },
    ],
  },
];

export default menuItems;
